site_name: Poulpe EtherCAT stack
repo_url: https://github.com/pollen-robotics/poulpe_ethercat_controller
edit_uri: https://github.com/pollen-robotics/poulpe_ethercat_controller/blob/develop/docs/
# repo_name: poulpe_ethercat_controller
copyright: |
  Copyright &copy; 2025 Pollen Robotics
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - shell
    - bash
    - python
    - terminal
    - console
  hljs_style: github
  custom_dir: docs/custom_theme/
  logo: img/favicon.ico

not_in_nav:
   api

extra_css:
  - extras/override.css

markdown_extensions:
  - callouts
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  