title: Poulpe EtherCAT
description: A quick guide to the Poulpe Ethercat controller
theme: just-the-docs

# GitHub Pages base URL
baseurl: "/poulpe_ethercat_controller" # Change this to match your GitHub repository name
url: "https://pollen-robotics.github.io/"

# Build settings
permalink: pretty
markdown: kramdown
highlighter: rouge

# Enable search
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true


# Exclude files from Jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

aux_links:
  Github Repository: https://github.com/pollen-robotics/poulpe_ethercat_controller