title: Poulpe ethercat controller docs
description: A quick guide to the Poulpe Ethercat controller
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github Repository: https://github.com/pollen-robotics/poulpe_ethercat_controller